config:
  repo: https://github.com/WorldHealthOrganization/nginx-ingress-whitelister.git
  tag: envoy
bundle:
  name: gateway-ca-bundle-envoy
  namespace: default
  repo: https://github.com/WorldHealthOrganization/tng-participants-dev.git 
clienttrafficpolicy:
  name: xfcc-policy
  namespace: default
job: 
  schedule: '*/50 * * * *'
